User authorization
Innowise-training/educationalsystem pull request #3
Opened 2023-08-25 13:47 UTC by 01thn

Generation a JWT for user login

2023-08-25 13:55 UTC, MikleGod commented on educationapplication/src/main/resources/application.yaml
> +    secret-key: secret
Also move it in a profile

2023-08-25 13:55 UTC, MikleGod commented on educationapplication/src/main/resources/application.yaml
> +    password: ${DB_PASSWORD:postgres}
Add application-local.yaml and set those properties there (eg DB_USER: root)

2023-08-25 13:55 UTC, MikleGod commented on modules/urm/api/src/main/java/com/innowise/educationalsystem/controller/AuthController.java
> +    public ResponseEntity<String> login(@RequestBody @Valid LoginRequestDto request,
new line after '('

2023-08-25 13:55 UTC, MikleGod commented on modules/urm/impl/src/main/java/com/innowise/educationalsystem/service/AuthService.java
> +    String loginUser(LoginRequestDto request, Long subscriptionId) throws NoSuchUserException, UserWrongCredentials;
Return a JwtDto here. (It might be still simle dto with one string field)

2023-08-25 15:10 UTC, neorezuss commented on modules/urm/api/src/main/java/com/innowise/educationalsystem/controller/AuthController.java
> +    public AuthController(AuthService authService) {
инжектим бины через @ReqArg конструктор

2023-08-25 15:10 UTC, neorezuss commented on modules/urm/api/src/main/java/com/innowise/educationalsystem/controller/AuthController.java
> +    public static final String CONTROLLER_MAPPING = "/api/v1/auth";
константы класса сделать private

2023-08-25 15:20 UTC, neorezuss requested changes

2023-08-25 15:20 UTC, neorezuss commented on modules/urm/impl/src/main/java/com/innowise/educationalsystem/exception/NoSuchUserException.java
> +public class NoSuchUserException extends Exception {
кастомные исключения наследуем от RuntimeException, плюс убрать отовсюду throws NoSuchUserException,
 UserWrongCredentials

2023-08-25 15:20 UTC, neorezuss commented on modules/urm/impl/src/main/java/com/innowise/educationalsystem/entity/User.java
> +@Table(name = "users")
упорядочить аннтоации лесенкой по возрастанию длины

2023-08-25 15:20 UTC, neorezuss commented on modules/urm/impl/src/main/java/com/innowise/educationalsystem/entity/User.java
> +    private Long id;
давай сразу поменяем на uuid

2023-08-25 15:20 UTC, neorezuss commented on modules/urm/impl/src/main/java/com/innowise/educationalsystem/repository/UserRepository.java
> +@Repository
аннотация @Repository не нужна

2023-08-25 15:29 UTC, neorezuss commented on modules/urm/impl/src/main/java/com/innowise/educationalsystem/service/AuthServiceImpl.java
> +    private boolean authenticateUser(LoginRequestDto request, UserResponseDto foundUser) throws UserWrongCredentials {
давай сделаем void и уберем return, тогда в вызывающем методе просто вызов методе просто authenticateUser(request, response) без if

2023-08-25 15:35 UTC, neorezuss commented on educationapplication/pom.xml
> +        <dependency>
impl не нужен

2023-08-28 08:15 UTC, neorezuss approved these changes

2023-08-28 08:51 UTC, MikleGod commented on educationapplication/src/main/resources/application-local.yaml
> +    token-expire: 1h
end of file

2023-08-28 08:51 UTC, MikleGod commented on modules/urm/api/src/main/java/com/innowise/educationalsystem/controller/AuthController.java
> +                                        @RequestBody @Valid LoginRequestDto request,
2 tabs

2023-08-28 08:51 UTC, MikleGod commented on modules/urm/impl/docker-compose.yaml
> +      - POSTGRES_DB=db_auth
Empty line at EOF

2023-08-28 08:51 UTC, MikleGod commented on modules/urm/impl/src/main/java/com/innowise/educationalsystem/service/AuthServiceImpl.java
> +        if (!passwordEncoder.matches(request.getPassword(), foundUser.getPassword()))
Brackets

2023-08-28 08:51 UTC, MikleGod commented on modules/urm/impl/src/main/java/com/innowise/educationalsystem/service/AuthServiceImpl.java
> +        userByUsername.orElseThrow(() -> new NoSuchUserException("User with such username doesn't exist"));
Shouldn't tell the users that the nickname doesn't exist. eg "Nickname or pass is wrong" is better.

2023-08-28 12:37 UTC, MikleGod approved these changes

2023-08-28 13:28 UTC, Lelikbjmak approved these changes

2023-08-28 15:26 UTC, merged